run:
	curl 127.0.0.1:8088/loginForm -d 'user=manu&password=123'
	curl 127.0.0.1:8088/loginJSON -H 'Content-Type: application/json' -d '{"user":"manu","password":"123"}'
	curl 127.0.0.1:8088/loginForm -H 'Content-Type: application/json' -d '{"user":"manu","password":"123"}'

